### ISSUE TITLE
Support multiple google APIs

### ISSUE THREAD

**Issue by fredrikbonander** [ef-ctx/ng.cx.google.drive#1]
To be able to support multiple google APIs this repository should be split in two:
- `cx.google` contains `google.client` and `google.client`
- `cx.google.drive` contains `google.drive`, has `cx.google` as a dependency 

And add a new one:
- `cx.google.analytics` contains `google.analytics`, has `cx.google` as a dependency 

_Should the repositories contain the prefix `cx.`? And if they do should all classes be hava the path `cx.google.*`? or should `cx` be omitted?_

The current export to `window` with `window.cxGoogleDrive` seems like a bit odd pattern. The new export would be `window.cx.google.*`

New additions to all repositories:
- .d.ts definition that defines the entire public api

**Comment by JaimeBeneytez** [comment]
1. Split cx.google : I like the idea :+1:  
2. `cx` prefix I think they should as the cox mark `cx.google` is great
3. 100% agree on `window.cx.<module>` cxGoogleDrive is a bit odd

Thank a lot @fredrikbonander

**Comment by jamesbrobb** [comment]
yeah looks good :+1:
